### ISSUE TITLE
Add images to README

### ISSUE THREAD

**Issue by rkayaith** [troggo/todo#1]

**Comment by rkayaith** [comment]
![screenshot_20170131-012217](https://cloud.githubusercontent.com/assets/1134272/22454484/1fadb70c-e754-11e6-8128-b0274206234a.png)

**Comment by troggo** [comment]
![screenshot_20170131-012217](https://cloud.githubusercontent.com/assets/1134272/22454492/2f7a58a2-e754-11e6-8206-59c4f144b404.png)

**Comment by rkayaith** [comment]
![screenshot_20170131-012224](https://cloud.githubusercontent.com/assets/1134272/22454508/4e11a2f2-e754-11e6-8277-f4641364ad44.png)
